[profile.default]
fail-fast = false
failure-output = "immediate-final"
status-level = "pass"
final-status-level = "flaky"

[profile.local]
fail-fast = true
failure-output = "immediate"
status-level = "pass"

[profile.ci]
fail-fast = false
retries = 1
failure-output = "immediate-final"
status-level = "fail"
final-status-level = "slow"